version: '3'

services:
  database:
    image: mongo

  backend:
    environment:
      - DB_URI=database
    links:
      - database
    depends_on:
      - database
    build: ./express-backend
    ports:
      - "3000:3000"
      - "8000:8000"

  frontend:
    links:
      - backend
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_PATH=http://backend:3000/api
      - REACT_APP_FRONTEND_PATH=${WEB_URL}
      - REACT_APP_SOCKET_PATH=http://backend:8000
      - REACT_APP_OMISE_PKEY=pkey_test_5e08bof53jrfb8vi6fa
    build: ./react-frontend
    ports:
      - "80:5000"

