version: '3'

services:
  database:
    image: mongo

  backend:
    environment:
      - DB_URI=database
    links:
      - database
    depends_on:
      - database
    build: ./express-backend
    ports:
      - "3000:3000"
      - "8000:8000"

  frontend:
    links:
      - backend
    depends_on:
      - backend
    build: ./react-frontend
    ports:
      - "80:5000"

